Northwind.Web/Controllers/ProductsOnSaleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Northwind.Services.Abstraction;
using NorthwindContracts.Dto.Order;
using NorthwindContracts.Dto.OrderDetail;
using NorthwindContracts.Dto.Product;
using System;
using System.Threading.Tasks;

namespace Northwind.Web.Controllers
{
    public class ProductsOnSaleController : Controller
    {
        private IServiceManager _serviceManager;

        public ProductsOnSaleController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        // GET: ProductsOnSaleController
        public async Task<ActionResult> Index()
        {
            var productOnSale = await _serviceManager.ProductService.GetProductOnSale(false);
            return View(productOnSale);
        }

        [HttpPost]
        public async Task<ActionResult> CreateOrder(ProductDto productDto)
        {
            if(ModelState.IsValid)
            {
                var products = productDto;
                var order = new OrderForCreateDto
                {
                    OrderDate = DateTime.Now,
                    RequiredDate = DateTime.Now.AddDays(3)
                };
                var orderDetail = new OrderDetailForCreateDto
                {
                    ProductId = products.ProductId,
                    UnitPrice = (decimal)products.UnitPrice,
                    Quantity = 0,
                    Discount = 0
                };
                _serviceManager.ProductService.CreateOrder(order, orderDetail);
                return RedirectToAction(nameof(Index));
            }
            return View(productDto);
        }

        // GET: ProductsOnSaleController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productOnSale = await _serviceManager.ProductService.GetProductOnSaleById((int)id, false);
            if (productOnSale == null)
            {
                return NotFound();
            }
            return View(productOnSale);
        }

            // GET: ProductsOnSaleController/Create
            public ActionResult Create()
        {
            return View();
        }

        // POST: ProductsOnSaleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductsOnSaleController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProductsOnSaleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductsOnSaleController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductsOnSaleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Northwind.Web/Views/ProductsOnSale/Details.cshtml
@model NorthwindContracts.Dto.Product.ProductDto

@{
    ViewData["Title"] = "Details";
}
@using (Html.BeginForm("CreateOrder",
"ProductsOnSale", FormMethod.Post))
{

    @Html.HiddenFor(model => model.ProductId)

    <div class="col-md">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col md-4">
                    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            @foreach (var item in Model.ProductPhotos)
                            {
                                if (Model.ProductPhotos.FirstOrDefault() == item)
                                {
                                    <div class="carousel-item active">
                                        <img class="card-img card-img-left" src="@Url.Content("~/Resources/Images/" + item.PhotoFilename)" alt="Card image">
                                    </div>
                                }
                                else
                                {
                                    <div class="carousel-item">
                                        <img class="card-img card-img-left" src="@Url.Content("~/Resources/Images/" + item.PhotoFilename)" alt="Card image">
                                    </div>
                                }
                            }
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>

                <div class="col md-8">
                    <div class="card-body">
                        <h2 class="card-title">@Html.DisplayFor(model => model.ProductName)</h2>
                        <br>
                        <br>
                        <h4 class="pb-1 mb-4">
                            @Html.LabelFor(model => model.UnitPrice) :
                            @Html.HiddenFor(model => model.UnitPrice)
                            @Html.DisplayFor(model => model.UnitPrice)
                        </h4>
                        <br>
                        <br>
                        <h4 class="pb-1 mb-4">
                            @Html.LabelFor(model => model.Category.CategoryName) :
                            @Html.DisplayFor(model => model.Category.CategoryId)
                        </h4>
                        <br>
                        <br>
                        <h4 class="pb-1 mb-4">
                            @Html.LabelFor(model => model.UnitsInStock) :
                            @Html.DisplayFor(model => model.UnitsInStock)
                        </h4>
                        <br>
                        @*@Html.TextBox("QuantityPerUnit",1,new{@type="number"})*@

                        <div class="css-h82t6w-unf-quantity-editor">
                            <button aria-label="Kurangi 1" class="css-199ul1b" tabindex="-1" disabled="">
                                <svg class="unf-icon" viewBox="0 0 24 24" width="18px" height="18px" fill="var(--NN300, #BFC9D9)" style="display: inline-block; vertical-align: middle;">
                                    <path d="M20 12.75H4a.75.75 0 110-1.5h16a.75.75 0 110 1.5z"></path>
                                </svg>
                            </button>
                            <input id="qty-editor-atc" aria-valuenow="1" aria-valuemin="1" aria-valuemax="836" class="css-197wjuk-unf-quantity-editor__input"data-unify="QuantityEditor" role="spinbutton" type="text" value="1">
                            <button aria-label="Tambah 1" class="css-199ul1b" tabindex="-1">
                                <svg class="unf-icon" viewBox="0 0 24 24" width="18px" height="18px" fill="var(--GN500, #00AA5B)" style="display: inline-block; vertical-align: middle;">
                                    <path d="M20 11.25h-7.25V4a.75.75 0 10-1.5 0v7.25H4a.75.75 0 100 1.5h7.25V20a.75.75 0 101.5 0v-7.25H20a.75.75 0 100-1.5z"></path>
                                </svg>
                            </button>
                        </div>
                        <br>
                        <br>
                        <a asp-action="AddCart" class="btn btn-outline-primary">
                            <i class='bx bxs-cart-add'><span>  Add to Cart</span></i>
                        </a>
                        <button type="submit" class="btn btn-primary"><span>  Checkout  </span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div>
        <a asp-action="Edit" asp-route-id="">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
}

Northwind.Web/Views/ProductsOnSale/Index.cshtml
@model IEnumerable<NorthwindContracts.Dto.Product.ProductDto>


<h4 class="text-capitalize">Product On Sale</h4>

@foreach(var item in Model)
{
<div class="col-md-6 col-xl-4">
    <a asp-action="Details" asp-route-id="@item.ProductId">
    <div class="card mb-3">
      <img class="card-img-top" src="@Url.Content("../Resources/Images/" + item.ProductPhotos.FirstOrDefault().PhotoFilename)" alt="Card image cap">
          <div class="card text-center">
            <div class="card-body">
            <h5 class="card-title">@Html.DisplayFor(modelItem => item.ProductName)</h5>
            <br>
            @Html.DisplayNameFor(model => model.FirstOrDefault().UnitPrice) :
            @Html.DisplayFor(modelItem => item.UnitPrice)
            <br>
            @Html.DisplayNameFor(model => model.FirstOrDefault().UnitsInStock) :
            @Html.DisplayFor(modelItem => item.UnitsInStock)
      </div>
    </div>
    </div>
    </a>
    </div>
}